-- Tripti Jewellers: authentication, catalogue, customer accounts and admin data.
-- Run this once in the Supabase SQL Editor for project iecxxyoatjzfnbjzepsk.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case when lower(coalesce(new.email, '')) = 'triptijewellers4826@gmail.com' then 'admin' else 'customer' end
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = case when public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end,
    role = case when excluded.email = 'triptijewellers4826@gmail.com' then 'admin' else public.profiles.role end,
    updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email, full_name, role)
select
  id,
  lower(coalesce(email, '')),
  coalesce(raw_user_meta_data ->> 'full_name', ''),
  case when lower(coalesce(email, '')) = 'triptijewellers4826@gmail.com' then 'admin' else 'customer' end
from auth.users
where email is not null
on conflict (id) do update set
  email = excluded.email,
  role = case when excluded.email = 'triptijewellers4826@gmail.com' then 'admin' else public.profiles.role end,
  updated_at = timezone('utc', now());

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
-- Public catalogue policies also evaluate this helper for anonymous visitors.
-- auth.uid() is null for them, so the function safely returns false.
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text not null,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= price),
  stock integer not null default 0 check (stock >= 0),
  image_url text not null default 'images/hero-jewellery.png',
  image_position text not null default 'center',
  image_alt text not null default '',
  badge text not null default '',
  featured boolean not null default false,
  description text not null default '',
  details jsonb not null default '[]'::jsonb check (jsonb_typeof(details) = 'array'),
  sizes jsonb not null default '[]'::jsonb check (jsonb_typeof(sizes) = 'array'),
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Home',
  full_name text not null,
  phone text not null,
  address_line text not null,
  city text not null,
  state text not null,
  pincode text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('TJ-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  user_id uuid not null references auth.users(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  customer_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  subtotal integer not null default 0 check (subtotal >= 0),
  shipping integer not null default 0 check (shipping >= 0),
  total integer not null default 0 check (total >= 0),
  payment_method text not null default 'To be confirmed',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price integer not null check (price >= 0),
  quantity integer not null check (quantity between 1 and 10),
  size text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.wishlist_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, product_id)
);

create table if not exists public.site_settings (
  id smallint primary key default 1 check (id = 1),
  announcement text not null default 'Complimentary insured shipping across India',
  whatsapp_number text not null default '919999999999',
  upi_id text not null default 'thetriptiedit@upi',
  support_email text not null default 'triptijewellers4826@gmail.com',
  free_shipping_minimum integer not null default 999 check (free_shipping_minimum >= 0),
  standard_shipping integer not null default 79 check (standard_shipping >= 0),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  image_url text not null default '',
  link_url text not null default 'shop.html',
  button_label text not null default 'Shop now',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_products_category_active on public.products(category, is_active);
create index if not exists idx_products_featured_active on public.products(featured, is_active) where featured = true;
create index if not exists idx_orders_user_created on public.orders(user_id, created_at desc);
create index if not exists idx_orders_status_created on public.orders(status, created_at desc);
create index if not exists idx_addresses_user on public.addresses(user_id);
create index if not exists idx_wishlist_user on public.wishlist_items(user_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at before update on public.categories for each row execute procedure public.set_updated_at();
drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at before update on public.products for each row execute procedure public.set_updated_at();
drop trigger if exists set_addresses_updated_at on public.addresses;
create trigger set_addresses_updated_at before update on public.addresses for each row execute procedure public.set_updated_at();
drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at before update on public.orders for each row execute procedure public.set_updated_at();
drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at before update on public.site_settings for each row execute procedure public.set_updated_at();
drop trigger if exists set_banners_updated_at on public.banners;
create trigger set_banners_updated_at before update on public.banners for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.site_settings enable row level security;
alter table public.banners enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles for select to authenticated
using ((select auth.uid()) = id or (select public.is_admin()));
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read" on public.categories for select to anon, authenticated
using (is_active or (select public.is_admin()));
drop policy if exists "categories_admin_write" on public.categories;
create policy "categories_admin_write" on public.categories for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select to anon, authenticated
using (is_active or (select public.is_admin()));
drop policy if exists "products_admin_write" on public.products;
create policy "products_admin_write" on public.products for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "addresses_own" on public.addresses;
create policy "addresses_own" on public.addresses for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "orders_select_own_or_admin" on public.orders;
create policy "orders_select_own_or_admin" on public.orders for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));
drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update" on public.orders for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "order_items_select_own_or_admin" on public.order_items;
create policy "order_items_select_own_or_admin" on public.order_items for select to authenticated
using (
  exists (
    select 1 from public.orders
    where public.orders.id = order_items.order_id
      and (public.orders.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

drop policy if exists "wishlist_own" on public.wishlist_items;
create policy "wishlist_own" on public.wishlist_items for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "settings_public_read" on public.site_settings;
create policy "settings_public_read" on public.site_settings for select to anon, authenticated using (true);
drop policy if exists "settings_admin_write" on public.site_settings;
create policy "settings_admin_write" on public.site_settings for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "banners_public_read" on public.banners;
create policy "banners_public_read" on public.banners for select to anon, authenticated
using (is_active or (select public.is_admin()));
drop policy if exists "banners_admin_write" on public.banners;
create policy "banners_admin_write" on public.banners for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

revoke all on public.profiles, public.categories, public.products, public.addresses, public.orders, public.order_items, public.wishlist_items, public.site_settings, public.banners from anon, authenticated;
grant select on public.categories, public.products, public.site_settings, public.banners to anon, authenticated;
grant select on public.profiles, public.addresses, public.orders, public.order_items, public.wishlist_items to authenticated;
grant insert, update, delete on public.categories, public.products, public.addresses, public.orders, public.order_items, public.wishlist_items, public.site_settings, public.banners to authenticated;
grant update (full_name, phone, updated_at) on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

insert into public.categories (name, slug, display_order) values
  ('Gold', 'gold', 1),
  ('Diamond', 'diamond', 2),
  ('Earrings', 'earrings', 3),
  ('Daily Wear', 'daily-wear', 4),
  ('Gemstone', 'gemstone', 5),
  ('Wedding', 'wedding', 6),
  ('Gifting', 'gifting', 7),
  ('Under 50K', 'under-50k', 8)
on conflict (name) do update set slug = excluded.slug, display_order = excluded.display_order;

insert into public.products
  (id, name, slug, category, price, old_price, stock, image_url, image_position, image_alt, badge, featured, description, details, sizes, display_order)
values
  (1, 'Saanjh Gold Necklace', 'saanjh-gold-necklace', 'Gold', 89999, 94999, 10, 'images/hero-jewellery.png', '72% center', 'Ornate gold necklace displayed on burgundy velvet', 'Bestseller', true, 'A graceful gold necklace with heritage-inspired detailing, made for celebrations that become family stories.', '["22 karat gold","Intricate handcrafted finish","Purity certificate included"]'::jsonb, '[]'::jsonb, 1),
  (2, 'Aarohi Diamond Ring', 'aarohi-diamond-ring', 'Diamond', 54999, null, 15, 'images/hero-jewellery.png', '68% 78%', 'Diamond ring arranged on a warm ivory stone surface', 'New', true, 'A refined diamond ring with a light-catching floral setting for proposals, milestones and everyday radiance.', '["18 karat gold","Certified natural diamonds","Complimentary ring-size assistance"]'::jsonb, '["10","12","14","16","18"]'::jsonb, 2),
  (3, 'Meher Drop Earrings', 'meher-drop-earrings', 'Earrings', 28999, null, 18, 'images/hero-jewellery.png', '91% 48%', 'Pair of detailed gold drop earrings with diamond accents', 'Festive edit', true, 'Elegant drop earrings that balance traditional motifs with a light, contemporary silhouette.', '["22 karat gold","Secure push-back closure","Designed for occasion wear"]'::jsonb, '[]'::jsonb, 3),
  (4, 'Nitya Gold Hoops', 'nitya-gold-hoops', 'Daily Wear', 18499, null, 24, 'images/hero-jewellery.png', '82% 66%', 'Polished gold hoops in a luxury jewellery arrangement', 'Everyday icon', false, 'Polished gold hoops with an easy profile and a secure fit for effortless everyday dressing.', '["18 karat gold","Lightweight construction","Secure clasp"]'::jsonb, '[]'::jsonb, 4),
  (5, 'Emerald Noor Pendant', 'emerald-noor-pendant', 'Gemstone', 42999, null, 8, 'images/hero-jewellery.png', '64% 42%', 'Gold pendant necklace with fine stone detailing', 'Limited', true, 'A luminous pendant inspired by garden geometry, finished with a vivid emerald-toned centre stone.', '["18 karat gold","Emerald-toned centre stone","Adjustable chain included"]'::jsonb, '[]'::jsonb, 5),
  (6, 'Vanya Bridal Necklace Set', 'vanya-bridal-necklace-set', 'Wedding', 159999, null, 4, 'images/hero-jewellery.png', '70% 38%', 'Grand gold bridal necklace and matching earrings on burgundy velvet', 'Bridal', true, 'A statement bridal necklace with matching earrings, composed to frame ceremonial looks with warmth and grandeur.', '["22 karat gold","Necklace and matching earrings","Private styling appointment available"]'::jsonb, '[]'::jsonb, 6),
  (7, 'Shagun Gold Coin', 'shagun-gold-coin', 'Gifting', 15999, null, 30, 'images/hero-jewellery.png', '76% 58%', 'Gold jewellery presented on a rich burgundy and ivory setting', 'Gift-ready', false, 'A beautifully presented gold keepsake for weddings, festivals, new beginnings and meaningful milestones.', '["24 karat gold","Tamper-evident presentation card","Gift packaging included"]'::jsonb, '[]'::jsonb, 7),
  (8, 'Prisha Pearl Bracelet', 'prisha-pearl-bracelet', 'Under 50K', 32999, null, 12, 'images/hero-jewellery.png', '86% 72%', 'Fine bracelet displayed with gold and diamond jewellery', 'Under ₹50K', false, 'A delicate pearl-and-gold bracelet designed for birthdays, gifting and understated occasion wear.', '["18 karat gold","Cultured freshwater pearls","Adjustable clasp"]'::jsonb, '[]'::jsonb, 8)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  category = excluded.category,
  price = excluded.price,
  old_price = excluded.old_price,
  stock = public.products.stock,
  image_url = excluded.image_url,
  image_position = excluded.image_position,
  image_alt = excluded.image_alt,
  badge = excluded.badge,
  featured = excluded.featured,
  description = excluded.description,
  details = excluded.details,
  sizes = excluded.sizes,
  display_order = excluded.display_order;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1), true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read" on storage.objects for select to public
using (bucket_id = 'product-images');
drop policy if exists "product_images_admin_insert" on storage.objects;
create policy "product_images_admin_insert" on storage.objects for insert to authenticated
with check (bucket_id = 'product-images' and (select public.is_admin()));
drop policy if exists "product_images_admin_update" on storage.objects;
create policy "product_images_admin_update" on storage.objects for update to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()))
with check (bucket_id = 'product-images' and (select public.is_admin()));
drop policy if exists "product_images_admin_delete" on storage.objects;
create policy "product_images_admin_delete" on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()));

create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_address text,
  p_payment_method text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_number text := 'TJ-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  v_email text;
  v_subtotal integer := 0;
  v_shipping integer := 0;
  v_free_shipping integer := 999;
  v_standard_shipping integer := 79;
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_size text;
begin
  if v_user_id is null then
    raise exception 'Please sign in before placing an order.';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Your shopping bag is empty.';
  end if;

  select email into v_email from public.profiles where id = v_user_id;
  if v_email is null then
    raise exception 'Customer profile was not found.';
  end if;

  insert into public.orders (id, order_number, user_id, customer_name, email, phone, address, payment_method)
  values (v_order_id, v_order_number, v_user_id, trim(p_customer_name), v_email, trim(p_phone), trim(p_address), coalesce(nullif(trim(p_payment_method), ''), 'To be confirmed'));

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(1, least(10, coalesce((v_item ->> 'quantity')::integer, 1)));
    v_size := coalesce(v_item ->> 'size', '');

    select * into v_product
    from public.products
    where id = (v_item ->> 'id')::bigint and is_active = true
    for update;

    if not found then
      raise exception 'A product in your bag is no longer available.';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Not enough stock for %.', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_quantity);
    insert into public.order_items (order_id, product_id, product_name, price, quantity, size)
    values (v_order_id, v_product.id, v_product.name, v_product.price, v_quantity, v_size);
    update public.products set stock = stock - v_quantity where id = v_product.id;
  end loop;

  select free_shipping_minimum, standard_shipping
  into v_free_shipping, v_standard_shipping
  from public.site_settings where id = 1;

  v_shipping := case when v_subtotal >= coalesce(v_free_shipping, 999) then 0 else coalesce(v_standard_shipping, 79) end;
  update public.orders
  set subtotal = v_subtotal, shipping = v_shipping, total = v_subtotal + v_shipping
  where id = v_order_id;

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'subtotal', v_subtotal,
    'shipping', v_shipping,
    'total', v_subtotal + v_shipping
  );
end;
$$;

revoke all on function public.place_order(text, text, text, text, jsonb) from public;
grant execute on function public.place_order(text, text, text, text, jsonb) to authenticated;
